import { Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "./_Components/Header";
import { ClerkProvider } from '@clerk/nextjs'
const inter = Roboto({ subsets: ['latin'], weight: '700' })
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} antialiased`}>
          <NextTopLoader />

          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>

  );
}
